### ISSUE TITLE
"Video tutorials" preview imgs are broken

### ISSUE THREAD

**Issue by zxcat** [broxus/ton-atomic-swap#1]
Screenshot:
![Screenshot-2020-09-28](https://user-images.githubusercontent.com/550974/94469279-81f2dd00-01ce-11eb-9722-1f5a261e3956.png)

**Comment by pavlovdog** [comment]
Hi @zxcat! Thanks for your attention. YouTube video thumbnail not supported by the GitHub natively, so the images replaced with a simple link.
